### ISSUE TITLE
PyNUTError Connection Refused

### ISSUE THREAD

**Issue by nvonbenken** [mihai-cindea/nut-influxdb-exporter#12] opened 2020-11-22 16:47 UTC
Hi, getting the following error:

```
Connecting to InfluxDB host:192.168.1.15, DB:nut
Connected successfully to InfluxDB
INFLUXDB_DATABASE: nut
INFLUXDB_USER:
INFLUXDB_PORT: 8086
INFLUXDB_HOST: 192.168.1.15
NUT_USER: None
UPS_NAME ups
INTERVAL: 21.0
VERBOSE: true
Connecting to NUT host 192.168.1.15:3493
[DEBUG] Class initialization...
[DEBUG] -> Host = 192.168.1.15 (port 3493)
[DEBUG] -> Login = 'None' / 'None'
[DEBUG] Connecting to host
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/nut2.py", line 97, in _connect
self._srv_handler = telnetlib.Telnet(self._host, self._port,
File "/usr/local/lib/python3.8/telnetlib.py", line 218, in __init__
self.open(host, port, timeout)
File "/usr/local/lib/python3.8/telnetlib.py", line 235, in open
self.sock = socket.create_connection((host, port), timeout)
File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
raise err
File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/src/nut-influxdb-exporter.py", line 47, in <module>
ups_client = PyNUTClient(host=nut_host, port=nut_port, login=nut_username, password=nut_password, debug=(verbose == 'true'))
File "/usr/local/lib/python3.8/site-packages/nut2.py", line 70, in __init__
self._connect()
File "/usr/local/lib/python3.8/site-packages/nut2.py", line 112, in _connect
raise PyNUTError("Socket error.")

nut2.PyNUTError: Socket error.
```

I have verified my InfluxDB IP and port. Any idea what might be causing this?

**Comment by mcindea** [comment] 2020-11-22 18:12
It seems it cannot connect to NUT daemon, I had the same problem where the default thing on UnRaid listened on the same port, and I had to kill it before starting NUT. However it seems that you have nothing listening on that port.
Can you check that NUT is actually running? maybe on another port?
```
netstat -plan
```
might help

**Comment by nvonbenken** [comment] 2020-11-22 18:17
Running that shows me two references to NUT.

```
root@Spartan:~# netstat -plan | grep nut
unix  2      [ ACC ]     STREAM     LISTENING     21656486 25645/usbhid-ups     /var/run/nut/usbhid-ups-ups
unix  3      [ ]         STREAM     CONNECTED     21658660 25645/usbhid-ups     /var/run/nut/usbhid-ups-ups
```

I can see my UPS in UnRaid
![image](https://user-images.githubusercontent.com/6497977/99911904-74853b00-2cc5-11eb-9b5b-c2ccc8dc4055.png)

**Comment by mcindea** [comment] 2020-11-22 22:16
alright, but do you have "NUT Network UPS Tools" app running? Note the "NUT settings" here:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/5544886/99918563-04ec6b80-2d18-11eb-9fd0-6686fc532c2e.png">

This was designed to work with the "NUT Network UPS Tools" Unraid app, the default UPS thing from Unraid should actually be disabled:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/5544886/99918605-509f1500-2d18-11eb-9931-e86f45abf07f.png">

The reason I created this was that the regular APC daemon was not compatible with my CyberPower UPS, however depending on what UPS you have it might or not be the case for you.

You can find this plugin under Apps if you don't have it already:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/5544886/99918661-d7ec8880-2d18-11eb-87f7-35e883f85992.png">

**Comment by nvonbenken** [comment] 2020-11-22 22:37
Yes, NUT Network UPS Tools is running and UPS Settings is stopped. 

Anything here look incorrect?
NUT Network UPS Tools
![image](https://user-images.githubusercontent.com/6497977/99919095-43b6fd00-2ce9-11eb-9722-c535ab6b5dd8.png)

**Comment by mcindea** [comment] 2020-11-22 22:44
this is what I have:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/5544886/99919251-93fb8280-2d1c-11eb-98fb-46ea0e380a0d.png">

I assume you might have to set "UPS Port" to `auto` or `3493` (I remember this being the default before)

**Comment by nvonbenken** [comment] 2020-11-22 23:19
I tried to give that a shot - toggled "Start Network UPS Tool service" to No, put auto in for "UPS Port", but now the NUT Network UPS Tools won't turn back on. I switched "Start Network UPS Tool service" and the status still shows stopped. I also rebooted my server and that didn't change anything. 

`netstat -plan | grep nut` gives no results now. Nothing suspect in the system log either. Not sure what the issue is now.

**Comment by mcindea** [comment] 2020-11-22 23:21
so in NUT settings you actually need "Start Network UPS tool service" to yes. Did you try port 3493 instead of auto?

**Comment by mcindea** [comment] 2020-11-22 23:24
btw I also had to stop the default UPS APC daemon from Settings => UPS Settings => Start APC UPS daemon => No because it was somehow conflicting with NUT, not sure if it's the case for you too.

**Comment by nvonbenken** [comment] 2020-11-22 23:25
Yes, 

![image](https://user-images.githubusercontent.com/6497977/99920218-09049300-2cf0-11eb-939e-9e11d517764c.png)

![image](https://user-images.githubusercontent.com/6497977/99920235-19b50900-2cf0-11eb-8409-318a9746a2f9.png)

**Comment by mcindea** [comment] 2020-11-22 23:26
On netstat I have something like this:
```
root@Rick:~# netstat -plan | grep nut
unix  2      [ ACC ]     STREAM     LISTENING     748631   20211/usbhid-ups     /var/run/nut/usbhid-ups-ups
unix  3      [ ]         STREAM     CONNECTED     746868   20211/usbhid-ups     /var/run/nut/usbhid-ups-ups
root@Rick:~# netstat -plan | grep 3493
tcp        0      0 0.0.0.0:3493            0.0.0.0:*               LISTEN      20283/upsd          
tcp        0      0 127.0.0.1:42828         127.0.0.1:3493          ESTABLISHED 20287/upsmon        
tcp        0      0 127.0.0.1:3493          127.0.0.1:42828         ESTABLISHED 20283/upsd          
tcp        0      0 172.17.0.1:3493         172.17.0.3:44096        ESTABLISHED 20283/upsd          
root@Rick:~# 
```

**Comment by mcindea** [comment] 2020-11-22 23:28
Note to self: add option to read from the socket file instead of port

**Comment by mcindea** [comment] 2020-11-22 23:30
Btw I noticed that to restart the NUT daemon if it's stopped, you can simply set "Start Network UPS Tools service" to "No" so the "Apply" button appears, but don't hit Apply yet, simply change it back to "Yes" and then hit Apply.

**Comment by nvonbenken** [comment] 2020-11-23 00:28
Doing that I just get this in the log but it stays stopped.

`Nov 22 19:27:52 Spartan ool www[8214]: /usr/local/emhttp/plugins/nut/scripts/start`

**Comment by mcindea** [comment] 2020-11-23 07:22
alternatively, you can also try to start it manually just to check what is wrong:
```
root@Rick:/var/log# /usr/local/emhttp/plugins/nut/scripts/start
Writing nut config
Updating permissions...
Network UPS Tools - UPS driver controller 2.7.4.1
Network UPS Tools - Generic HID driver 0.55 (2.7.4.1)
USB communication driver 0.43
Duplicate driver instance detected (PID file /var/run/nut/usbhid-ups-ups.pid exists)! Terminating other driver!
                                                                               
Broadcast message from root@Rick (somewhere) (Mon Nov 23 06:07:46 2020):       
                                                                               
Communications with UPS ups@127.0.0.1 lost                                     
                                                                               

Using subdriver: CyberPower HID 0.5
nut upsd is running...
nut upsmon is running...
root@Rick:/var/log# 
```

**Comment by nvonbenken** [comment] 2020-11-23 14:16
Accoriding to the documentation I should be using the `usbhid-ups` driver.
![image](https://user-images.githubusercontent.com/6497977/99972091-1a8b8080-2d6c-11eb-8da9-703d71fb6f56.png)

Selecting that then manually trying to start the service by running the script gives me this:
```
root@Spartan:/usr/local/emhttp/plugins/nut/scripts# ./start
Writing nut config
Updating permissions...
Network UPS Tools - UPS driver controller 2.7.4.1
Network UPS Tools - Generic HID driver 0.55 (2.7.4.1)
USB communication driver 0.43
This TrippLite device (09ae:3024) is not (or perhaps not yet) supported
by usbhid-ups. Please make sure you have an up-to-date version of NUT. If
this does not fix the problem, try running the driver with the
'-x productid=3024' option. Please report your results to the NUT user's
mailing list <nut-upsuser@lists.alioth.debian.org>.
```

Looking back at my previous screenshot I sent, I was using `Blazor_usb` as the driver. Switching back to that gives me this:
```
root@Spartan:/usr/local/emhttp/plugins/nut/scripts# ./start
Writing nut config
Updating permissions...
Network UPS Tools - UPS driver controller 2.7.4.1
Network UPS Tools - Megatec/Q1 protocol USB driver 0.20 (2.7.4.1)
No supported devices found. Please check your device availability with 'lsusb'
and make sure you have an up-to-date version of NUT. If this does not help,
try running the driver with at least 'subdriver', 'vendorid' and 'productid'
options specified. Please refer to the man page for details about these options
(man 8 blazer_usb).

Driver failed to start (exit status=1)
```

I can see the UPS with `lsusb`:
```
root@Spartan:/usr/local/emhttp/plugins/nut/scripts# lsusb | grep AVR
Bus 005 Device 002: ID 09ae:3024 Tripp Lite AVR750U    
```

**Comment by mcindea** [comment] 2020-11-23 14:44
Not sure what the version of NUT daemon app on Unraid is to be honest since I don't maintain that one.
I'd open a ticket with NUT, I see they have a similar issue: https://github.com/networkupstools/nut/issues/166
My guess is that the device id might not be in the list and should be added similarly to [this PR](https://github.com/networkupstools/nut/commit/6767555bc28e82f4f9b8f719f1ccf5b18cca6d67)
I see that AVR750U is simply not in the list: https://github.com/networkupstools/nut/blob/6767555bc28e82f4f9b8f719f1ccf5b18cca6d67/drivers/tripplite-hid.c#L227-L234

EDIT: Actually it is, but only as `1007` and not `3024` as your error message says: `09ae:3024`: https://github.com/networkupstools/nut/blob/1a1f1211216275e677f2a41d5f517f80aa50a616/drivers/tripplite-hid.c#L81

**Comment by mcindea** [comment] 2020-11-24 19:10
Closing this since I think it's unrelated to this plugin, but feel free to re-open it if there's anything I can help you with. Cheers!

**Closed as completed by mcindea** 2020-11-24 19:10 UTC
